name: linux_ci_asan_noasm

on: [push, pull_request]

jobs:
  build-native:
    name: "${{ matrix.compiler }} - ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        compiler: ["clang"]
    env:
      CC: "${{ matrix.compiler }}"
      ARCH: native
      CFLAGS: "-ggdb -fsanitize=address"
      LDFLAGS: "-fsanitize=address"
      CTEST_OUTPUT_ON_FAILURE: 1
      ENABLE_ASM: OFF
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@main
      - name: "Run tests"
        run: ./scripts/test
