name: macos_ci

on: [push, pull_request]

jobs:
  build-native:
    strategy:
      matrix:
        os: [macos-13, macos-12]
        arch: [arm64, x86_64]
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    env:
      ARCH: ${{ matrix.arch }}
    name: ${{ matrix.os }} - ${{ matrix.arch }}
    steps:
    - name: Install packages for macos
      run: brew install automake
    - uses: actions/checkout@main
    - name: Run CI script
      run: ./scripts/test
